### ISSUE TITLE
Migrate project to unleash/unleash-client-python

### ISSUE THREAD

**Issue by ivanklee86** [Unleash/unleash-client-python#1]
- [x] Update CI to use new repo.
- [x] Update setup.py and push minor rev. (+ security fix?)
- [x] Update badges
- [ ] Set up GH-pages
- [ ] Tweak package in Pypi
- [ ] Archive old project.

**Comment by ivarconr** [comment]
I've accepted the ci integration 😎

**Comment by ivanklee86** [comment]
Thank you! ^^

**Comment by ivanklee86** [comment]
@ivarconr This is done! =)

**Comment by ivarconr** [comment]
Woop woop Great work! Again thanks for the effort and making it easy to use unleash also in python. Hope this can benefit the community ;)

I will update the main readme when I have some time with a computer again ;)
