### ISSUE TITLE
Does Unleash Client Python supports Dynamic headers?

### ISSUE THREAD

**Issue by ryanermita** [Unleash/unleash-client-python#104]
I got the same problem with [Support for setting headers dynamically](https://github.com/Unleash/unleash-client-node/issues/151) from unleash-client-node but mine is for Python.

I saw that dynamic headers are already supported in [unleash-client-node](https://github.com/Unleash/unleash-client-node/pull/152) and [unleash-client-java](https://github.com/Unleash/unleash-client-java#dynamic-custom-http-headers). 
I was wondering if there's an implementation of this feature in unleash-client-python.

If none, what is your recommended work around?

Thank you!

**Comment by ivanklee86** [comment]
Good morning!

Modifying the `unleash_custom_headers` class variable (a plain old dictionary) on the client will update the request headers the next time the client sends an API request to the server.  

Something like the following should work:
```Python
my_client.unleash_custom_headers['Authorization'] = "MyNewAuthorizationCode"
```

Having said that, I've mainly done this using integration scripts for testing purposes.  Could you let me know how it works for you? (If it works great, I'll add it to the documentation.)

**Comment by ryanermita** [comment]
Hi @ivanklee86, 
I test your scenario, `unleash_custom_headers` are being updated but the workers still using the headers from the client initialization. I validated it by logging the headers on my unleash client and on my python test script using the `unleash-client-python`

I tried to re-initialize the client using `client.initialize_client()` after changing the headers in the assumption that it would also re-initialize the workers but it raises this error:
```
    raise SchedulerAlreadyRunningError
apscheduler.schedulers.SchedulerAlreadyRunningError: Scheduler is already running
```
