### ISSUE TITLE
In-memory features are not updated when initialized from a Celery worker

### ISSUE THREAD

**Issue by kmkr** [Unleash/unleash-client-python#105]
**Describe the bug**

We use unleash-client-python in our code in both gunicorn and Celery environments. The `fetch_and_load_features` method runs in the background in both cases. However, updates are only propagated to the client in gunicorn environments. Clients initialized in Celery environments don't receive updates to it's _memory_ instance (`self.features`). Updates _are_ propagated to the cache, so I can workaround the problem by running `load_features` in the `is_enabled` function:

```python
  def is_enabled(self,
                   feature_name: str,
                   context: dict = {},
                   default_value: bool = False,
                   fallback_function: Callable = None) -> bool:
        # Docstring removed for brevity
        context.update(self.unleash_static_context)

        # Workaround the problem by loading features from the cache:
        load_features(self.cache, self.features, self.strategy_mapping)

        if self.is_initialized:
            try:
                return self.features[feature_name].is_enabled(context, default_value)
       # more code removed for brevity
```

The problem is perhaps related to how the `apsscheduler.BackgroundScheduler` works/not works together with Celery, but I'm not sure. 

Do you have any suggestions to solve this problem--without manually loading the features from cache?

**To Reproduce**

1. Initiate the Unleash client in a Celery worker
2. Wait for the first `fetch_and_load_features` to complete.
3. Update a toggle in the Unleash interface, for example from enabled to disabled.
4. Wait for the background worker to fetch and load features.
5. Call `is_enabled` on the feature. The feature's state is not updated but should be.

**Comment by ivanklee86** [comment]
Hello!

I, unfortunately, haven't really given unleash-client-python a shot in Celery.  I'll give it a try but may take a lil' bit as work is being work-ey.

I had a few general questions:
* Are you running [Celery in Flask](https://flask.palletsprojects.com/en/1.1.x/patterns/celery/) (or the app-factory equivalent)?  
* If you set the log level to DEBUG you should see some log statements from apscheduler (example below).  By any chance is anything showing up in the celery task?

```
2020-09-15 13:01:32,216 - apscheduler.scheduler - INFO - Scheduler started
2020-09-15 13:01:32,216 - apscheduler.scheduler - DEBUG - Looking for jobs to run
2020-09-15 13:01:32,216 - apscheduler.scheduler - DEBUG - No jobs; waiting until a job is added
2020-09-15 13:01:32,217 - apscheduler.scheduler - INFO - Added job "fetch_and_load_features" to job store "default"
2020-09-15 13:01:32,217 - apscheduler.scheduler - DEBUG - Looking for jobs to run
2020-09-15 13:01:32,217 - apscheduler.scheduler - DEBUG - Next wakeup is due at 2020-09-15 13:01:47.216962-04:00 (in 14.999569 seconds)
2020-09-15 13:01:32,217 - apscheduler.scheduler - INFO - Added job "aggregate_and_send_metrics" to job store "default"
2020-09-15 13:01:32,217 - apscheduler.scheduler - DEBUG - Looking for jobs to run
2020-09-15 13:01:32,217 - apscheduler.scheduler - DEBUG - Next wakeup is due at 2020-09-15 13:01:47.216962-04:00 (in 14.999192 seconds)
```

**Comment by kmkr** [comment]
Hi and thank you for your reply :sunflower: 

> Are you running Celery in Flask (or the app-factory equivalent)?

No. We are running Celery as a Heroku worker process. Not sure if it gives you any value, but in case it does here's our flags for running Celery:

`celery worker -A <appName> -l info -c 3 -Q default`

> If you set the log level to DEBUG you should see some log statements from apscheduler (example below). By any chance is anything showing up in the celery task?

Absolutely. The background tasks run in both gunicorn and Celery environments:

```
8:22:35 AM worker.1 |  [2020-09-16T06:22:35+0000 INFO/apscheduler.executors.default request_id= ] Running job "fetch_and_load_features (trigger: interval[0:00:15], next run at: 2020-09-16 06:22:35 UTC)" (scheduled at 2020-09-16 06:22:35.074064+00:00)
8:22:35 AM worker.1 |  [2020-09-16T06:22:35+0000 INFO/UnleashClient.utils request_id= ] Getting feature flag.
8:22:35 AM worker.1 |  [2020-09-16T06:22:35+0000 INFO/apscheduler.executors.default request_id= ] Job "fetch_and_load_features (trigger: interval[0:00:15], next run at: 2020-09-16 06:22:50 UTC)" executed successfully
# ... truncated
8:31:20 AM worker.1 |  [2020-09-16T06:31:20+0000 INFO/apscheduler.executors.default request_id= ] Job "aggregate_and_send_metrics (trigger: interval[0:01:00], next run at: 2020-09-16 06:32:20 UTC)" executed successfully
8:31:20 AM worker.1 |  [2020-09-16T06:31:20+0000 INFO/apscheduler.executors.default request_id= ] Job "fetch_and_load_features (trigger: interval[0:00:15], next run at: 2020-09-16 06:31:35 UTC)" executed successfully
```
When `fetch_and_load_features` completes in the background task, I'd expect the Celery's `client.features` to be updated but it's not. I've confirmed the background task successfully updated _it's_ Unleash client in-memory state, but for some reason that state is not updated in the Unleash client running in the "normal" (or "non-background") Celery thread. Perhaps the objects/instances of Unleash clients are copied in a Celery/apscheduler environment and therefore not sharing in-memory state?

**Comment by ivanklee86** [comment]
Thanks for the info!  I'm going to try and reproduce with [this](https://github.com/ivanklee86/celery-flask-factory) demo repo I've used in the past.

Will let you know how it goes! :)

**Comment by ivanklee86** [comment]
Notes for the morning:
* Able to reproduce on [this commit](https://github.com/ivanklee86/celery-flask-factory/commit/c8076274a22b362d3213f7a27635b23337f3dddf) by flipping the `ivan-celery-test` .
* Logs:
```
some_worker | [2020-09-18 09:37:36,731: INFO/MainProcess] Received task: server.controller.tasks.wait_task[d16d82cd-e868-4a78-bb67-45f5391201c3]
some_worker | [2020-09-18 09:37:36,735: INFO/ForkPoolWorker-2] Feature toggle status for feature ivan-celery-test: True
some_worker | [2020-09-18 09:37:36,735: WARNING/ForkPoolWorker-2] Unleash Worker check: True
```

**Comment by emersonmx** [comment]
These days I went through something similar. The solution found was to initialize unleash in `worker_process_init` so that `fetch_and_load_features` runs in the background.
https://docs.celeryproject.org/en/stable/userguide/signals.html#worker-process-init
