### ISSUE TITLE
Sentry spam in case external host is not available sometimes

### ISSUE THREAD

**Issue by Keramblock** [Unleash/unleash-client-python#122]
**Describe the bug**
Error spams in case if external host is not available sometimes(see attached screen) and it spams an error in Sentry.io(in my case)

**Expected behavior**
If host is unavailable - we should try to reconnect to it without errors

**Additional context**
<img width="836" alt="изображение" src="https://user-images.githubusercontent.com/3233532/105152235-f5bb4b80-5b17-11eb-9cee-7f1a82b8d635.png">

**Comment by Keramblock** [comment]
https://github.com/Unleash/unleash-client-python/blob/c87f4e509a04a0ef9db6f0cd163c80f7f1ec985e/UnleashClient/api/metrics.py#L42

**Comment by Keramblock** [comment]
or MB we should use warning instead of exception?

**Comment by ivanklee86** [comment]
I think `warning` versus `exception` logging makes sense for API calls.  I'll include it in the next release!

**Comment by ivanklee86** [comment]
This is released in v3.6.0. :)

**Comment by Keramblock** [comment]
thanks a lot! =)
