### ISSUE TITLE
Support different types of caching, like in-memory or redis caching

### ISSUE THREAD

**Issue by hossam-zoover** [Unleash/unleash-client-python#126]
**Is your feature request related to a problem?**

I cannot use unleash-client-python as it needs to create a caching directory and this is not possible as  I have an app deployed on Google App Engine and it's read only file system.

**Describe the solution you'd like**

Support different types of caching, like in-memory or redis caching.

**Describe alternatives you've considered**

I'm blocked as the only way you support is File caching with filecache lib

**Comment by ivarconr** [comment]
I think it makes sense for the SDKs to accept a extra parameter for a class implementing a defined interface for storing and retrieving backups. 

In some scenarios it can even make sense to be able to disable the persistent backup all together.
