### ISSUE TITLE
Report metrics only for toggles that are actually used

### ISSUE THREAD

**Issue by fwpheckel** [Unleash/unleash-client-python#129]
**Describe the bug**
The python client currently reports metrics for all feature toggles, whether or not they have actually been used by the client

**To Reproduce**
Instantiate an unleash client with metrics reporting activated, connecting to a host with multiple toggles defined. Use one toggle. Observe that in the unleash UI for an unused toggle, the client is reported under "seen in applications".

**Expected behavior**
The unleash client does not appear under "seen in applications" for toggles that have not been used

**Additional context**
This looks like a direct consequence of https://github.com/Unleash/unleash-client-python/blob/master/UnleashClient/periodic_tasks/send_metrics.py#L18

which could probably be resolved with:

```
    for feature_name in features.keys():
        if not (features[feature_name].yes_count or features[feature_name].no_count):
            continue
        feature_stats = {
            features[feature_name].name: {
                "yes": features[feature_name].yes_count,
                "no": features[feature_name].no_count
            }
        }
```

**Comment by ivanklee86** [comment]
Ack, that certainly makes sense.  :) I'll roll it into the next release (which is mainly some under-the-hood fixes/refactoring).

**Comment by ivarconr** [comment]
I concur! This is also in line with other SDKs, to only send metrics for toggles being queried by the user.

**Comment by fwpheckel** [comment]
Thanks, I'll keep an eye out! Apologies for not just providing a PR, but at least the patch should be pretty small.

**Comment by ivanklee86** [comment]
No problem!  This is in `v3.6.2` which is released on PyPi now. =)
