### ISSUE TITLE
Silent "Error checking feature flag" errors

### ISSUE THREAD

**Issue by romanvog** [Unleash/unleash-client-python#150]
We are running a generic script that pulls values from unleash using python client for different services. Not all flags exist for each service, and we're getting "Error checking feature flag" for those that don't. 
In our case these errors aren't needed and would like to be able to silent them to avoid errors in logs.

**Comment by aberenshtein** [comment]
+1

**Comment by yoramshai** [comment]
+1

**Comment by ivarconr** [comment]
@ivanklee86

**Comment by ivanklee86** [comment]
Makes sense!  I'm going to add a configuration so people can set the log level for these messages. :)

**Comment by ivanklee86** [comment]
In `v4.3.0`, you can specify the `verbose_log_level` during UnleashClient initialization.  It's set to 30 (warn) by default, but you can set a numerical log level aka https://docs.python.org/3/library/logging.html#logging-levels . :)
