### ISSUE TITLE
Add e2e tests for UnleashClient

### ISSUE THREAD

**Issue by ivanklee86** [Unleash/unleash-client-python#16]
**Is your feature request related to a problem? Please describe.**
Integration testing (atm) involves spinning up a local instance, running a script that creates an UnleashClient, and looping through some feature flags.

This would be nice to automate, as hopefully it'd help catch issues like #7 .

**Describe the solution you'd like**
* Add [docker-compose](https://circleci.com/docs/2.0/docker-compose/) w/[unleash-docker](https://github.com/Unleash/unleash-docker).
* Import data for feature flags.
* Automate server-side checks?

**Describe alternatives you've considered**
* Use [Heroku](https://unleash.herokuapp.com/#/features).

**Additional context**

**Comment by ivarconr** [comment]
I have been thinking about adding metrics verifications to the client-specifcation tests also. Just haven't had the time.
