### ISSUE TITLE
UnleashClient not respecting changes to constraints

### ISSUE THREAD

**Issue by glowe** [Unleash/unleash-client-python#178]
**Describe the bug**

The `UnleashClient` is not reflecting constraint changes made in the Unleash UI in a multi-process, threaded django/uwsgi context. When we change the constraint for our Default strategy, we observe that the `apscheduler` job updates the `FileCache`. But, when we make a a call to `UnleashClient::is_enabled`, we don't get the correct value. What's strange is we get the right behavior in the django shell on the same host. It appears that the client is using the constraint that it picked up when it was first initialized for all `is_enabled` calls.

Our understanding is that `UnleashClient` should be a singleton. As such, we instantiate and initialize it during application startup, assigning it as a module level variable. 

We're running the following versions of software:

- `python` 3.7.5
- `django` 2.2.24
- `unleashclient` 4.4.0
- `uwsgi` 2.0.15-debian

**To Reproduce**

1. Setup a Default strategy that uses `environment IN <some environment>` that will return true when `UnleashClient::is_enabled` is called.
2. Change `<some environment>` such that `UnleashClient::is_enabled` should return false.
3. Wait a minute.
4. Observe that the `FileCache` is updated.
5. Make a call to `UnleashClient::is_enabled` and observe that it still returns true.

**Expected behavior**

After some amount of time, `UnleashClient::is_enabled` should respect the constraint change made in the server and what is present in the `FileCache`.

**Comment by ivarconr** [comment]
Hi, thanks for reporting this. We are able to reproduce a similar behavior using `uwsgi` with multiple threads and processes at the same time. 

The SDK works fine in `uwsgi` with multiple threads, but we see that problem appears when multiple processes is enabled and when `uwsgi` spawn child processes. 

We are looking in to how to solve this.

**Comment by vintersnow** [comment]
@ivarconr Hello, I have the same issue on the latest SDK (5.7.1) and Django 3.2.15.
Is this issue solved or any workaround exists?
