### ISSUE TITLE
Regression: Errors thrown if HTTP 304 returned

### ISSUE THREAD

**Issue by janLo** [Unleash/unleash-client-python#185]
If the client (5.0.0) is used against a Gitlab Feature flag server it produces a lot of these errors:
~~~
Unleash Client feature fetch failed due to exception: JSONDecodeError('Expecting value', '')
~~~

This happens because the response body from Gitlab is ampty if a HTTP 304 is returned. The fix is simple: do not try to parse the response if the server indicates that nothing has changed. Looking at the code this should be achievable by returning None or an empty dict from here if the response code was 304:
https://github.com/Unleash/unleash-client-python/blob/10b81f3cbe7f80bef2ccb41840127cb8e81d548f/UnleashClient/api/features.py#L62

**Comment by ilee-asapp** [comment]
This fix is in v5.0.1 which was published this morning.  Thanks for the report and the PR! :)
