### ISSUE TITLE
Client registration failed; returns 401

### ISSUE THREAD

**Issue by subbuvenk18** [Unleash/unleash-client-python#19]
**Describe the bug**
I was trying to use the unleash python client on my Django implementation and see a 401 on `client.intialitze()` call with the message `"unleash client registration failed."`. This is followed up with the message `"unleash metrics submission failed."` printed out in regular intervals.
I dug through the code and this seems to come from the `register_client ` method in `UnleashClient/api/register.py`. I was curious if this was a GitLab permissions issue and tried to manually make the request from my Python shell which had the same fate. I'm confident that the request goes through and the error is not due to logic in `except` clause. I couldn't find any more docs on GitLab or on this repo about client registration. Nonetheless, I'm able to use the client for feature flagging without issues other than my log being filled up with the initial message and constant metric submission failure methods. 

**To Reproduce**
Steps to reproduce the behavior(in Python shell):
1. from UnleashClient import UnleashClient
2. uc = UnleashClient(...)
3. uc.intialize_client()
4. See `unleash client registration failed.`
5. See `unleash metrics submission failed.` printed on regular intervals

**Expected behavior**
I hope we can add some more documentation about client registration and how that works in case of GitLab Feature Flags. If there's no provision to do so with GitLab, an alternative would be much appreciated.

**Logs**
`unleash client registration failed.`
`unleash metrics submission failed.`*<forever>

**Comment by ivanklee86** [comment]
@subbuvenk18 Unfortunately, I don't have access to GitLab's feature flag feature.  I'll see if I can get  open source/nonprofit access. =)

In the meantime, is there any indication from GitLab's side that the feature flag is working (e.g. client is registered, metrics are showing)?

**Comment by ivanklee86** [comment]
@subbuvenk18 --Unfortunately, I don't have access to GitLab's feature flag feature.-- (Found a way, ironically with their Open Source request repo.) 

I suspect the issue is that Gitlab is basically blocking requests to the BASE_URL/clients/register and BASE_URL/clients/metrics endpoints.

@ivarconr Is this something you've seen in other clients? (And if so, how would you propose handling this?)

**Comment by ivarconr** [comment]
Most clients allow you to disable registration and metrics.

**Comment by ivanklee86** [comment]
Ah cool! :) Can do that + add documentation.

**Comment by ivanklee86** [comment]
@subbuvenk18 This is fixed in v2.3.0.  Documentation on suggested config is at the bottom of: https://github.com/Unleash/unleash-client-python/blob/master/docs/unleashclient.md

**Comment by subbuvenk18** [comment]
@ivanklee86 @ivarconr Thanks for the update. That totally works for me. 
Also, I wanted to add that I tried disabling metrics using the already present flag and that didn't stop the `unleash metrics submission failed.`. I will follow up on it after testing 👍

**Comment by subbuvenk18** [comment]
I can now confirm that it works as expected with the new flag. Thanks!
