### ISSUE TITLE
feat: Add support for new constraint operators

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-python#191]
I have written a summary In this issue: https://github.com/Unleash/unleash/issues/856#issuecomment-1027910183

Client-specifications: https://github.com/Unleash/client-specification/pull/25

Node SDK reference implementation: https://github.com/Unleash/unleash-client-node/pull/289

**PS! we are still working out the UI and validating the actual protocol, but we are at > 93% certainty.**

**Comment by ivanklee86** [comment]
Tasks:
- [ ] Add `currentTime` to default Unleash context.
- [ ] Modify [Constraint initialization](https://github.com/Unleash/unleash-client-python/blob/main/UnleashClient/constraints/Constraint.py#L6) for new values (`caseInsensitive` -> `case_insensitive`, `inverted` 'value')
- [ ] Implement new conditionals.
- [ ] Add unit tests to Constraint object.
- [ ] Add spec tests.

Resources:

**Comment by ivarconr** [comment]
can we close this issue? 
https://github.com/Unleash/unleash-client-python/blob/main/CHANGELOG.md#v510

**Comment by ivanklee86** [comment]
Totally forgot about this issue.  It can indeed be closed!
