### ISSUE TITLE
Relax "Unable to get feature flag toggles" log message

### ISSUE THREAD

**Issue by povilasb** [Unleash/unleash-client-python#199]
**Is your feature request related to a problem? Please describe.**

1. `UnleashClient` produces these logs periodically:
```sh
WARNING: Unable to get feature flag toggles, using cached provisioning.
```

2. The source: https://github.com/Unleash/unleash-client-python/blob/f5900b8dadb140bf1a9e8420e2b380e9571c5847/UnleashClient/periodic_tasks/fetch_and_load.py#L30

3. This is a normal behavior and is triggered when response status code from unleash is 304: https://github.com/Unleash/unleash-client-python/blob/f5900b8dadb140bf1a9e8420e2b380e9571c5847/UnleashClient/api/features.py#L62
    i.e. no changes have been made to toggles

**Describe the solution you'd like**

Just use an info log message.

**Comment by karls** [comment]
You could argue that the log message itself is also a little bit misleading. It's implies that something went wrong — "Unable to get...". In reality the server responded with `304 Not Modified` which seems to instruct the client to use the cached version.

I think I'd even have that log level to DEBUG and re-word the message for clarity.

**Comment by ivanklee86** [comment]
Good point!  I've dropped it to `DEBUG` and rewrote the message. :)

**Comment by ivanklee86** [comment]
This is in `v5.1.2` :)

**Comment by karls** [comment]
Nice! Cheers. :-)

**Comment by povilasb** [comment]
Awesome, thank you!

**Comment by Natgho** [comment]
I think the issue is still persist, it should be silenced;
https://github.com/Unleash/unleash-client-java/commit/f9200c99f39dea092a5d89cface75c9a1965f2b9
