### ISSUE TITLE
Unleash Client feature fetch failed due to exception: SSLError

### ISSUE THREAD

**Issue by povilasb** [Unleash/unleash-client-python#201]
**Describe the bug**

`UnleashClient` for me produces around 1-2k errors like this per day:
```py
Unleash Client feature fetch failed due to exception: SSLError(MaxRetryError('HTTPSConnectionPool(host=\'us.app.unleash-hosted.com\', port=443): Max retries exceeded with url: /elowen/api/client/features (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, \'Unexpected EOF\')")))'))
```

I'm not 100% sure as I haven't tested the networking errors, but this seems a lot like TCP connection reset.
This may be very much a server error and not a client one, but hypothetically the client could reduce the number of errors with retries?
https://github.com/Unleash/unleash-client-python/blob/4c7bc98e7919f5f3ae91ca1c732337be61b2d17b/UnleashClient/api/features.py#L31

**Logs**

Here's the stack trace:
```py
SysCallError: (-1, 'Unexpected EOF')
  File "urllib3/contrib/pyopenssl.py", line 488, in wrap_socket
    cnx.do_handshake()
  File "OpenSSL/SSL.py", line 1991, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "OpenSSL/SSL.py", line 1693, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")

SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
  File "urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "urllib3/contrib/pyopenssl.py", line 494, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)

MaxRetryError: HTTPSConnectionPool(host='us.app.unleash-hosted.com', port=443): Max retries exceeded with url: /elowen/api/client/features (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
  File "requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))

SSLError: HTTPSConnectionPool(host='us.app.unleash-hosted.com', port=443): Max retries exceeded with url: /elowen/api/client/features (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
  File "UnleashClient/api/features.py", line 48, in get_feature_toggles
    resp = requests.get(base_url,
  File "requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
```

**Comment by ivarconr** [comment]
Thanks for reporting @povilasb 

For our understanding: 
- Did this change recently? 
- Is able to connect to the service at all?

**Comment by ivarconr** [comment]
(fyi: we did swap the default certificate eof last week from "us.app.unleash-hosted.com" to "*.app.unleash-hosted.com", so it could  potentially be some local certs being used maybe?)

**Comment by povilasb** [comment]
Alright, I'm gonna do some more testing, but in the meantime

1. I just started running Unleash client, so can't tell if this is a recent issue.
2. Most of the requests work just fine and only a fraction errors: 30-40 reqs/hour out of ~61440/hour that we make.
3. No proxies.
4. Env:
```sh
Debian 11 
Python==3.9.10
requests==2.22.0
OpenSSL 1.1.1k  25 Mar 2021
```

**Comment by povilasb** [comment]
Tested locally on Mac OS and then Debian 11 - sent over 60k requests multiple times from both environments, but never received a single TLS issue.
However, I'm in Europe.
And the software that produces the before mentioned issues is running in the cloud in US.
So I assume DNS resolves to a different server - haven't checked that though :)

**Comment by ivarconr** [comment]
would you be able to run that test on a server in us also? A simple way could be to deploy the app to "Heroku" or similar and select the US region. 

I find it a bit strange though if that should end up being any different.. We are using AWS issued Certificates and terminate the public certs in AWS ELB.

**Comment by akalex** [comment]
I have been experiencing kinda the same issue with SSL.
```
"Unleash Client feature fetch failed due to exception: HTTPSConnectionPool(host='...', port=443): Max retries exceeded with url: /api/client/features (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))"
```

**Comment by povilasb** [comment]
Retrying all HTTP requests up to 3 times solved these issues btw.
