### ISSUE TITLE
Feat: add support for bootstrapping

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-python#203]
Improve resilience by implementing the Bootstrap feature of Unleash. Feature write-up:
https://www.getunleash.io/blog/bootstrap-unleash-java-sdk-to-improve-the-resilience

Reference implementation: 
* Java SDK: https://github.com/Unleash/unleash-client-java/pull/131
* Node SDK: https://github.com/Unleash/unleash-client-node/pull/283/files

We need to bootstrap to be adapted to what makes sense in Pyhton. It should at least allow:
- manual passing of "json string of the full feature toggle configuration", 
- loading from file 
- loading from URL. 

If the user want to bootstrap from a URL we should probably try he actual Unleash API, and load the bootstrap URL as a fallback mechanism of the SDK fails to load it from the Unleash API. It will only load from bootstrap on the initial fetch.

**Comment by ivanklee86** [comment]
So the Python client:
* Fetches feature provisioning from Unleash.
* Saves feature provisioning to cache.
* [Uses cached provisioning](https://github.com/Unleash/unleash-client-python/blob/4c7bc98e7919f5f3ae91ca1c732337be61b2d17b/UnleashClient/loader.py#L73) to load feature flats.

We recently added [custom cache](https://docs.getunleash.io/unleash-client-python/customcache.html) which I think can be repurposed to add bootstrapping.  Maybe we can have some out-of-box custom caches?

Out of curiosity, hat are the common use cases for custom caches?  i.e. integration tests?

**Comment by ivarconr** [comment]
> Out of curiosity, hat are the common use cases for custom caches? i.e. integration tests?

The main reason would be to have some good defaults in the case you are unable to connect to Unleash API at startup. 

> We recently added [custom cache](https://docs.getunleash.io/unleash-client-python/customcache.html) which I think can be repurposed to add bootstrapping. Maybe we can have some out-of-box custom caches?

That makes sense. But would like to see some built in support for fetching from url or getting it passed in as a json blob. This is the same we have added for the node-sdk.

**Comment by ivanklee86** [comment]
This is in v5.2.0 that was just released! :)
