### ISSUE TITLE
Add retries to get_feature_toggles

### ISSUE THREAD

**Issue by janboll** [Unleash/unleash-client-python#217]
**Is your feature request related to a problem? Please describe.**
HTTP requests in get_feature_toggles might fail due to intermittent network issues. 

Since this is called quite often, it could create plenty of long stack traces, since the entire stack trace is printed: https://github.com/Unleash/unleash-client-python/blob/main/UnleashClient/api/features.py#L67

**Describe the solution you'd like**
Retry the request a couple of times and log only in situations where it does not recover.

I'd be happy to provide a proposal fo this.

**Comment by sighphyre** [comment]
HI @janboll, this sounds like a pretty good idea. It's one of those improvements that I think we're pretty unlikely to get to for a while, if you'd like to take a look that would be most welcome and hugely appreciated!

**Comment by janboll** [comment]
Hi @sighphyre, I created a PR that adds a custom HTTPAdapter. I saw, that the pipelines are blocked since cause execution needs to be permitted first. Can you please take a look?

**Comment by sighphyre** [comment]
Amazing, thank you! I've enabled the pipeline, I'll take a closer look at the code a bit later
