### ISSUE TITLE
Typo in not implemented "bootstraped" argument.

### ISSUE THREAD

**Issue by koffie** [Unleash/unleash-client-python#220]
**Describe the bug**
From https://docs.getunleash.io/unleash-client-python/unleashclient.html

```
class UnleashClient.UnleashClient(url: str, app_name: str, environment: str = 'default', instance_id: str = 'unleash-client-python', refresh_interval: int = 15, refresh_jitter: Optional[int] = None, metrics_interval: int = 60, metrics_jitter: Optional[int] = None, disable_metrics: bool = False, disable_registration: bool = False, custom_headers: Optional[dict] = None, custom_options: Optional[dict] = None, custom_strategies: Optional[dict] = None, cache_directory: Optional[str] = None, project_name: Optional[str] = None, verbose_log_level: int = 30, cache: Optional[BaseCache] = None):
"""
A client for the Unleash feature toggle system.

Parameters:

- url – URL of the unleash server, required.
- ...
- bootstraped – Whether cache has been boostrapped (i.e. pre-seeded) with Unleash configuration. When true, UnleashClient will use initial configuration until the client is initialized. See FileCache object for more information about bootstrapping.
"""
```

Note that there is a typo in the documentation of the "bootstraped" parameter. Additionally the bootstraped/bootstrapped argument is not even available as can be seen in the signature of the init function.

**To Reproduce**
```
>>> from UnleashClient import UnleashClient
>>> UnleashClient(bootstrapped=True)
Traceback (most recent call last):
  File "/Users/maartenderickx/.pyenv/versions/3.10.2/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: UnleashClient.__init__() got an unexpected keyword argument 'bootstrapped'
>>> UnleashClient(bootstraped=True)
Traceback (most recent call last):
  File "/Users/maartenderickx/.pyenv/versions/3.10.2/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: UnleashClient.__init__() got an unexpected keyword argument 'bootstraped'
```

**Expected behavior**
The documentation and the behaviour of the UnleashClient should be consistent. So either the bootstrapped parameter should be implemented, or it should be removed from the UnleashClient documentation.

**Extra info**
According to the source this problem is at least still existing in the 5.3.0 release https://github.com/Unleash/unleash-client-python/blob/af592d01b656b631296ef70c8558dd22db2ef34e/UnleashClient/__init__.py .

**Comment by ivanklee86** [comment]
Whoops, this is a holdover from an previous implementation.  The cache (or cache implementation) should be the [source of truth](https://github.com/Unleash/unleash-client-python/blob/main/UnleashClient/cache.py#L15) for whether it was bootstrapped.

I'll update the docs shortly to remove this!

**Comment by koffie** [comment]
Thanks, since I now know what the intended fix is, I made a pr for solving this. #222
