### ISSUE TITLE
Unleash apscheduler executor should not use `"default"` executor

### ISSUE THREAD

**Issue by macieyng** [Unleash/unleash-client-python#221]
**Is your feature request related to a problem? Please describe.**
We're using apscheduler in our project for 1.5 year now. We added unleash few months ago. Recently, we started to observe weird process/thread locking within apscheduler jobs. Today we looked into our and Unleash code and it turned out that we both were using the same executor. We had our own defined as 
```python
executors = {
   "default": ThreadPoolExecutor(1),
}
```
which - I believe, because I don't have skills to investigate that, but I've seen logs that could suggest that - clashes with the default executor that Unleash client is using. 

**Describe the solution you'd like**
- allow developers to change executor name, but use own executor with name partially random if no name is specified in initializer

**Describe alternatives you've considered**
- Unleash should create it's own executor with name partially random to prevent executor names clashing, e.i. `"unleash_executor_6f5a3n"`
- force developers to name the executor explicitly and let them know that there is apscheduler underneath

**Additional context**
Of course we made a mistake of using the default executor. We should've started with our own unique name. But that shows the behavior that may blow up someone else's application too. 

Suppose, they're using apscheduler for years. Recently, they decided to add a third party application that uses apscheduler which crashes the app. Now, the team has to make changes to the working app, so that it would accommodate a new third party. 

To me, this looks like giving up a drivers' seat to a hitchhiker, rather than inviting for a free ride on the drivers' rules. Third party should have all the set up needed for being self sufficient without a need to bother the host.

**Comment by ivanklee86** [comment]
Have you considered using different executors?  I haven't had the chance to use `apscheduler` for anything production-adjacent so curious. :)

I suspect the best approach might be to let people pass in the executor(s) they want, otherwise generate a random executor name.

**Comment by macieyng** [comment]
What do you mean by different executors? Like name them differently (we did that today and deployed to production) or use something different than `ThreadPoolExecutor`?

**Comment by ivanklee86** [comment]
@macieyng Sorry, realized that question didn't make a ton of sense in retrospect.  Could you take a 👀 at PR #223 and see if it makes sense from the perspective of someone who uses apscheduler?

**Comment by macieyng** [comment]
Yes! I love that PR ❤️  
You did something even better - folks will be able to pass their own scheduler, as per apscheduler [docs](https://apscheduler.readthedocs.io/en/3.x/userguide.html#basic-concepts): `Schedulers are what bind the rest together. You typically have only one scheduler running in your application.`

**Comment by macieyng** [comment]
@ivanklee86 thank you so much for fixing this issue! When it could be released? We're eager to upgrade asap 🙃

**Comment by ivanklee86** [comment]
v5.4.0 with this improvement is on Pypi now! :)
