### ISSUE TITLE
NOT_IN operator doesnt take inversion into account by returning early

### ISSUE THREAD

**Issue by brtknr** [Unleash/unleash-client-python#234]
**Describe the bug**

The issue was introduced here by returning `True` early instead of allowing invert condition to play out:
https://github.com/Unleash/unleash-client-python/commit/9aa528a78fe54df8efee0c4d929537693dccac28#diff-5a34048a72d9dbcc1cf64fe80a13119b0b40ee924c5cfc90a0352c30e7036ac4R184

**To Reproduce**

Create a NOT_IN strategy with inversion enabled. Pass context_value as None from the client.

**Expected behavior**
Inversion should take effect.

**Logs**
N/A

**Additional context**
N/A

**Comment by brtknr** [comment]
When will this be packaged into a new release?

**Comment by sighphyre** [comment]
@brtknr Released this morning in 5.5.0!

**Comment by brtknr** [comment]
Awesome, thank you!
