### ISSUE TITLE
Add Impression Events

### ISSUE THREAD

**Issue by sighphyre** [Unleash/unleash-client-python#238]
This is a feature that's implemented in most of the Unleash SDKs, it's currently not implemented here.

Reference documentation here: https://docs.getunleash.io/reference/impression-data

And reference PR implementing this in the dotnet SDK: https://github.com/Unleash/unleash-client-dotnet/pull/113

**Comment by ivanklee86** [comment]
What event system would you like to use?  I haven't used them much myself, but from a quick Google it doesn't look like there's a clear favorite.

[blinker](https://blinker.readthedocs.io/en/stable/) seems reasonably popular, updated, and parts of the pallets project.

**Comment by sighphyre** [comment]
Honestly, I'm in exactly the same boat. I've never needed an event system in Python so I have no opinions here. 

Blinker looks pretty reasonable. I think we should go with that

**Comment by ivanklee86** [comment]
[eventsourcing](https://github.com/pyeventsourcing/eventsourcing) is another one!

(Just tossing research here while I 🤔

**Comment by ivanklee86** [comment]
@sighphyre What GUID format do you expect for events?  [Here](https://docs.python.org/3/library/uuid.html) are the standard options for Python.

**Comment by sighphyre** [comment]
> @sighphyre What GUID format do you expect for events? [Here](https://docs.python.org/3/library/uuid.html) are the standard options for Python.

Any reason not to use a uuidv4()? That's my go to unless I need something special

**Comment by ilee-asapp** [comment]
I have seen some tweaks (i.e. namespacing) for massively distributed systems...but I suspect in most cases it's overkill and `When we're Google...` thinking. 😭 

I'll start with uuidv4() and we can see how if it fowls up in the wild...
