### ISSUE TITLE
Version of dependent modules not listed

### ISSUE THREAD

**Issue by nonchan7720** [Unleash/unleash-client-python#239]
**Describe the bug**

`ModuleNotFoundError: No module named 'apscheduler.job'` is printed at runtime

**To Reproduce**

1. `pipenv install UnleashClient`
2. Launching Applications
3. Error on startup. (`ModuleNotFoundError: No module named 'apscheduler.job'`)

Sample code is welcome!

**Expected behavior**

The correct version of `apscheduler` must be installed and running.

**Logs**
If applicable, add logs or output to help explain your problem.

The version of `apscheduler` installed is `4.0.0a2`.

**Additional context**

**Comment by ivanklee86** [comment]
I would recommend installing `apscheduler 3.x.x` as I haven't confirmed it'll work with the (long delayed but very interesting!) apscheduler 4.x.x.

I'll make a PR later today to set a "ceiling" on the dependency.

**Comment by nonchan7720** [comment]
Thank you!
