### ISSUE TITLE
Required dependencies are not installed with new `UnleashClient==5.7.0`.

### ISSUE THREAD

**Issue by stancld** [Unleash/unleash-client-python#262]
**Describe the bug**
Required dependencies are not installed with new `UnleashClient==5.7.0`.

**To Reproduce**

```
# Open a new venv
> python -m pip install UnleashClient==5.7.0
> python -c "from UnleashClient import UnleashClient"
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/stancld/miniconda3/envs/morgan/lib/python3.10/site-packages/UnleashClient/__init__.py", line 9, in <module>
    from apscheduler.executors.pool import ThreadPoolExecutor
ModuleNotFoundError: No module named 'apscheduler'
```

**Expected behavior**
`UnleashClient` during installation will install all required dependencies.

**Comment by joshzcold** [comment]
Our builds are currently effected with
```
 from UnleashClient.utils import LOGGER, log_resp_info
  File "/sm/venv/lib/python3.8/site-packages/UnleashClient/utils.py", line 6, in <module>
    import mmh3  # pylint: disable=import-error
ModuleNotFoundError: No module named 'mmh3'
```

**Comment by ivanklee86** [comment]
I've yank'd `v5.7.0`, uploaded `v5.7.1`, and tested installation (both with package and off Pypi) and integration tests works as expected.

@stancld / @joshzcold Would you mind giving it a shot again?

**Comment by joshzcold** [comment]
Previous errors have cleared for me. Thanks for the quick response 👏

**Comment by stancld** [comment]
Hi @ivanklee86, I can confirm everything works as expected for me as well.

Thank you very much for such prompt action! <3
