### ISSUE TITLE
Add ability to set request timeout

### ISSUE THREAD

**Issue by snuderl** [Unleash/unleash-client-python#264]
**Is your feature request related to a problem? Please describe.**
The initial unleash initialization is synchronous and can take a long time if network is down. The default request timeout is 30 seconds with 3 retries. Which is done twice both to call register client and then to poll the flags the first time which can add up to 3 minutes of wait time.

**Describe the solution you'd like**
Ability to easily override the default request time.

**Describe alternatives you've considered**
The main confusion is probably in the fact that unleash generally runs in the background, but then at the same time can fully block in these edge cases.

Right now we did some manual patching to the unelash library constant but that is very brittle and will probably break at some point and would much rather prevent to have a more standard way of doing this.

**Additional context**

**Comment by gastonfournier** [comment]
Hi @snuderl I think this is a fair request, I noticed this is hard coded in our constants: https://github.com/Unleash/unleash-client-python/blob/15c9000fc1d609c7966f89c210e050a9017269ed/UnleashClient/constants.py#L6-L7 

These defaults are good for most use cases, but if you have a special need, we're open to contributions. Feel free to raise a PR and add that as a parameterizable value.

**Comment by pransh15** [comment]
Hi @snosratiershad - great to hear that! ❤ 

Let us know if you need any help. 😄

**Comment by snosratiershad** [comment]
In progress of parameterizing `REQUEST_RETRIES`, I realized the retry policy is only applied to `get_feature_toggles` and not to other requests. should we consider the policy for other requests?

**Comment by snosratiershad** [comment]
Dear @nunogois, now we can close this issue as the PR merged.
