### ISSUE TITLE
Require python-dateutil>=2.8.1

### ISSUE THREAD

**Issue by felix-hilden** [Unleash/unleash-client-python#266]
**Describe the bug**
When installed with python-dateutil<2.8.1, importing `UnleashClient` raises "cannot import ParserError from dateutil.parser".

**Expected behavior**
UnleashClient would have been installed with the appropriate version restriction.

**Additional context**
Python 3.9, but I think it doesn't make a difference. The change to dateutil is [this one](https://github.com/dateutil/dateutil/pull/881).

This might make older versions of UnleashClient install in favor of the newest one if solvers decide that the restricted dateutil version wouldn't fit, but it's probably better to fix the issue.

**Comment by Tymek** [comment]
Thank your for reporting this. Would you like to contribute a fix? If not, I'll add it to our priorities internally.

**Comment by felix-hilden** [comment]
I can have a look next week if you haven't gotten to it! I know very little about the project, so if it's a trivial thing, feel free to just do it 👍🏿

**Comment by snosratiershad** [comment]
@Tymek, I've an idea. As I noticed, before 2.8.1 it raised ValueError instead of ParserError in the same cases. what if instead of requiring at least a 2.8.1 version of `dateutils`, check the version and use ValueError instead?

**Comment by snosratiershad** [comment]
Here's an example: https://github.com/Unleash/unleash-client-python/pull/273
