### ISSUE TITLE
Support semver >= 3.0.0 as a dependency

### ISSUE THREAD

**Issue by beljul** [Unleash/unleash-client-python#276]
**Is your feature request related to a problem? Please describe.**
I have a conflict with another package (https://github.com/flairNLP/flair) which requires semver<4.0.0,>=3.0.0.

**Describe the solution you'd like**
Could you please tell me if the unleash client could support semver >= 3.0.0 instead of enforcing semver < 3.0.0 ?

**Comment by ilee-asapp** [comment]
I pinned `semver` because - at the time of implementation - they mentioned 3.0.0 with API changes was on the horizen.

We can def. revisit that - I think most of the changes were unrelated to how `ucp` is using the library.  I'll see if

**Comment by chaitanya-parsana** [comment]
Hi, 
Trying to use unleash with Lancedb, and having the same issue with dependency resolution error on semver versioning.

**Comment by chaitanya-parsana** [comment]
I have a draft here: #280 
Please let me know if you'd like any changes.

**Comment by ivanklee86** [comment]
Apologies, life kind of ambushed me.

PR looks good, let me get a new release rolling. :)

**Comment by ilee-asapp** [comment]
This is in `v5.9.1` which is up on Pypi! :)

**Comment by beljul** [comment]
Sounds good to me, thanks a lot for your reactivity ! :pray:
