### ISSUE TITLE
Ability to configure request timeout and retries when instantiating a client

### ISSUE THREAD

**Issue by felix-hilden** [Unleash/unleash-client-python#290]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to configure request timeouts and retry counts from the client constructor.

**Describe the solution you'd like**
Similar args as #270 but on the client, but without the typos (#289)

**Describe alternatives you've considered**
I don't really see other alternatives, because the calls are buried in scheduled tasks.

**Comment by kwasniew** [comment]
@felix-hilden I created a PR https://github.com/Unleash/unleash-client-python/pull/292 to address your issue. Please let me know if it matches your expectations.

**Comment by felix-hilden** [comment]
Thank you for such a quick response! Looks good 👌🏿
