### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by josteinl** [Unleash/unleash-client-python#307]
Support for Python 3.12 would be much appreciated.

**Comment by ivanklee86** [comment]
We should def. add it to our CI processes but by-in-large our policy is to not use newer language features to ensure compatibility. I think in package metadata only shows lowest version (and honestly needs an update 😢 ).

Is there something in particular that is not working with `3.12`?

**Comment by josteinl** [comment]
It seems the `mmhash3` package (unmaintained?) you are using does not support 3.12. At least I had some problems installing it with poetry on windows.

**Comment by josteinl** [comment]
Just investigating a bit more around the [mmhash3](https://pypi.org/project/mmhash3) package. It is a fork of the [mmh3](https://pypi.org/project/mmh3/) package, that already has Python 3.12 support. 

So maybe the only thing that needs to be done here is replacing `mmhash3` with `mmh3`.

**Comment by sighphyre** [comment]
@josteinl Oh, thanks for checking that out. We actually originally moved off of that dependency because it didn't support Python 3.11 and wasn't being maintained. I suppose we can just move back to that

**Comment by ivanklee86** [comment]
Whoops, I forgot to make a release with this change. >< I'll publish it now.
