### ISSUE TITLE
Datetime constraints result in TypeError if currentTime is not provided or currentTime is not timezone-aware

### ISSUE THREAD

**Issue by jacob-indigo** [Unleash/unleash-client-python#323]
**Describe the bug**
A datetime constraint can be created in Unleash with a timezone-aware or timezone-naive ISO datetime string. If a timezone-aware datetime is used (which appears to be the default for the Unleash web app), the Python client will fail when evaluation that constraint if a timezone-naive datetime object/string is provided as the `currentTime` in the context. The same is true of the inverse (tz-naive constraint and tz-aware `currentTime`).  

This is mainly an issue if `currentTime` is not set in the context and the Unleash client provide its own `currentTime` value. If a user providers a `currentTime` value themselves, it's reasonable enough to require them to be consistent (all tz-aware or all tz-naive). But currently, if the default `currentTime` is used, it fails if the constraint is tz-aware. 

**Logs**

```
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by sighphyre** [comment]
Hey @jacob-indigo, would you mind providing a reproduction case for this? The Unleash webapp should always be returning a UTC time in the constraints. From a quick check, I can't seem to trigger a case where it isn't. If it is doing that then this issue is wider than just the Python SDK and I'd really like to be able to tackle at the source!

I see the PR, to be completely honest, your timing is terrible, the code that you've patched is about to go away in the next week in preparation for the next major version :sweat_smile:. I don't mind taking a change before we do the next major but I'd like to understand what it is that's occurring so that I can make sure it doesn't regress

**Comment by jacob-indigo** [comment]
I think I buried the lede a little. The webapp always sets the timezone but the Python SDK always DOES NOT. Resulting in date constraints always evaluating to false.

**Steps to reproduce:**
1. Create a new feature flag strategy with a `DATE_AFTER` constraint for some time in the past
```
curl --location --request POST 'https://<HOST>/api/admin/projects/default/features/test-feature/environments/development/strategies' \
    --header 'Authorization: INSERT_API_KEY' \
    --header 'Content-Type: application/json' \
    --data-raw '{
  "name": "flexibleRollout",
  "constraints": [
    {
      "contextName": "currentTime",
      "operator": "DATE_AFTER",
      "values": [],
      "caseInsensitive": false,
      "inverted": false,
      "value": "2024-11-12T00:00:00.000Z"
    }
  ],
  "parameters": {
    "rollout": "100",
    "stickiness": "default",
    "groupId": "test-feature"
  },
  "variants": [],
  "segments": [],
  "disabled": false
}'
```
2. Check if that feature flag is enabled using the Python client:
```python
client.is_enabled('test-feature')
```

**Actual behavior:** 
`is_enabled` returns `False` even though though the DATE_AFTER constraint is set to a time in the past. 

**Expected behavior:**
`is_enabled` returns `True`

**Workaround:**
Pass a timezone-aware `datetime` object in as part of the context
```python
client.is_enabled('test-feature', {
    "currentTime": datetime.now(timezone.utc)
})
```

**Additional context:**
If `currentTime` isn't explicitly passed in the context dict, UnleashClient will add it in [here](https://github.com/Unleash/unleash-client-python/blob/54f00b59428ecabcacb60e15554b216c3b9234d9/UnleashClient/constraints/Constraint.py#L200)
 by using `datetime.now()`. `datetime.now()` produces a timezone-naive `datetime` object. 

We then compare `currentTime` to the constraint time value which is parsed from an ISO datetime string into a `datetime` object [here](https://github.com/Unleash/unleash-client-python/blob/54f00b59428ecabcacb60e15554b216c3b9234d9/UnleashClient/constraints/Constraint.py#L143) using `dateutil`. If the ISO string has timezone info (e.g. ending in `Z`), a timezone-aware `datetime` object will be produced. 

We then compare `currentTime` to the constraint time ([here](https://github.com/Unleash/unleash-client-python/blob/54f00b59428ecabcacb60e15554b216c3b9234d9/UnleashClient/constraints/Constraint.py#L152)) resulting in a `TypeError` **ALWAYS** being raised.

The `TypeError` is caught [here](https://github.com/Unleash/unleash-client-python/blob/54f00b59428ecabcacb60e15554b216c3b9234d9/UnleashClient/constraints/Constraint.py#L247) and `False` is returned because that is the default value for `constraint_check`.

**Comment by sighphyre** [comment]
@jacob-indigo Thank you, very helpful details!

Merged your submission, going to do a patch release
