### ISSUE TITLE
feat: add support for variants

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-python#80]
I will add a proper description soon. Already supported by node and java client. 

Client-specifications for this feature: 
https://github.com/Unleash/client-specification/blob/master/specifications/08-variants.json

**Comment by ivanklee86** [comment]
Tasks:
- [ ] Create Variants object to encapsulate provisioning and logic.
- [ ] Update Strategy to load variations.
- [ ] Update Strategy to app

**Comment by ivanklee86** [comment]
Resources:
- [Beta docs](https://unleash.github.io/docs/beta_features)
