### ISSUE TITLE
Specifying default_value overrides real value

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [Unleash/unleash-client-python#99]
**Describe the bug**
Maybe I'm misunderstanding the purpose of `default_value` but the way I'm expecting it to work is:
1. If a flag exists, the `is_enabled` call uses the status of the flag.
2. If a flag **doesn't** exist, the `default_value` is used.

Instead, the `default_value` always seems to be used, even if the flag is present.

**To Reproduce**
1. Create a Flag: `myFlag`
2. Create code as such:
```
return str(client.is_enabled("myFlag"))
```
This will correctly grab the value of `myFlag` and `enable` or `disable` as appropriate.

Now adjust the code to:
```
return str(client.is_enabled("myFlag", default_value=True))
```
The return value will **always** by `True`, regardless of my real toggle status.

![image](https://user-images.githubusercontent.com/13639658/80780033-d60e7c80-8bb0-11ea-9a90-69edec83e88a.png)

**Comment by ivarconr** [comment]
You are correct, this is not the correct behavior. Need to investigate later when I have some time. 

@ivanklee86  corrected the behavior for fallback_function (https://github.com/Unleash/unleash-client-python/issues/85). Can you check if a fallback function can be a possible workaround for now?

**Comment by ivanklee86** [comment]
Thanks for the report!  I agree that the current implementation doesn't make a ton of sense - as Ivar mentioned I'd recommend using the `fallback_function` instead.  

I'll update the documentation to remove mention of the method and add a deprecation warning.  I'm planning on removing it next time we have a major version bump.

@ivarconr I think this is a hold-over from the initial client implementation.  In the [client specification](https://github.com/Unleash/unleash/blob/master/docs/client-specification.md) documentation it says:

```
The basic isEnabled method should also accept a default value. This should be used if the client does not know anything about a particular toggle. If the user does not specify a default value, false should be returned for unknown feature toggles.

Calling unleash with default value:

boolean value = unleash.isEnabled("unknownFeatureToggle", false);
//value==false because default value was used.
```
